export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSE_FAIL = 'FETCH_COURSE_FAIL';
export const FETCH_SUBJECT_SUCCESS = 'FETCH_SUBJECT_SUCCESS';
export const FETCH_SUBJECT_FAIL = 'FETCH_SUBJECT_FAIL';
export const FETCH_YEAR_SUCCESS = 'FETCH_YEAR_SUCCESS';
export const FETCH_YEAR_FAIL = 'FETCH_YEAR_FAIL';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAIL = 'FETCH_QUESTION_FAIL';

